file_format: "1"
id: corne
name: Corne
url: https://github.com/a741725193/zmk-corne-dongle
type: shield
requires: [pro_micro]
features:
  - keys
  - display
outputs:
  - usb
  - ble
siblings:
  - corne_peripheral_left
  - corne_peripheral_right
  - corne_central_dongle